/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v2.2/films/{id}': {
    /** Данный эндпоинт возвращает базовые данные о фильме. Поле <b>lastSync</b> показывает дату последнего обновления данных. */
    get: {
      parameters: {
        path: {
          /** kinopoisk film id */
          id: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            'application/json': components['schemas']['Film'];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Превышен лимит запросов(или дневной, или общий) */
        402: unknown;
        /** Фильм не найден */
        404: unknown;
        /** Слишком много запросов. Общий лимит - 20 запросов в секунду */
        429: unknown;
      };
    };
  };
  '/api/v2.2/films/{id}/seasons': {
    /** Данный эндпоинт возвращает данные о сезонах для сериала. */
    get: {
      parameters: {
        path: {
          /** kinopoisk film id */
          id: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            'application/json': components['schemas']['SeasonResponse'];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Превышен лимит запросов(или дневной, или общий) */
        402: unknown;
        /** Слишком много запросов. Общий лимит - 20 запросов в секунду */
        429: unknown;
      };
    };
  };
  '/api/v2.2/films/{id}/facts': {
    /** Данный эндпоинт возвращает список фактов и ошибок в фильме. <br> type - <b>FACT</b>, обозначает интересный факт о фильме. <br> type - <b>BLOOPER</b>, обозначает ошибку в фильме. */
    get: {
      parameters: {
        path: {
          /** kinopoisk film id */
          id: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            'application/json': components['schemas']['FactResponse'];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Превышен лимит запросов(или дневной, или общий) */
        402: unknown;
        /** Слишком много запросов. Общий лимит - 20 запросов в секунду */
        429: unknown;
      };
    };
  };
  '/api/v2.2/films/{id}/distributions': {
    /** Данный эндпоинт возвращает данные о прокате в разных странах. */
    get: {
      parameters: {
        path: {
          /** kinopoisk film id */
          id: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            'application/json': components['schemas']['DistributionResponse'];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Превышен лимит запросов(или дневной, или общий) */
        402: unknown;
        /** Слишком много запросов. Общий лимит - 20 запросов в секунду */
        429: unknown;
      };
    };
  };
  '/api/v2.2/films/{id}/box_office': {
    /** Данный эндпоинт возвращает данные о бюджете и сборах. */
    get: {
      parameters: {
        path: {
          /** kinopoisk film id */
          id: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            'application/json': components['schemas']['BoxOfficeResponse'];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Превышен лимит запросов(или дневной, или общий) */
        402: unknown;
        /** Слишком много запросов. Общий лимит - 20 запросов в секунду */
        429: unknown;
      };
    };
  };
  '/api/v2.2/films/{id}/awards': {
    /** Данный эндпоинт возвращает данные о наградах и премиях фильма. */
    get: {
      parameters: {
        path: {
          /** kinopoisk film id */
          id: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            'application/json': components['schemas']['AwardResponse'];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Превышен лимит запросов(или дневной, или общий) */
        402: unknown;
        /** Слишком много запросов. Общий лимит - 20 запросов в секунду */
        429: unknown;
      };
    };
  };
  '/api/v2.2/films/{id}/videos': {
    /** Данный эндпоинт возвращает трейлеры,тизеры,видео для фильма по kinopoisk film id. В данный момент доступно два site:  <br/> <ul><li>YOUTUBE - в этом случае <b>url</b> это просто ссылка на youtube видео.</li><li>KINOPOISK_WIDGET - в этом случае <b>url</b> это ссылка на кинопоиск виджет. Например https://widgets.kinopoisk.ru/discovery/trailer/123573?onlyPlayer=1&autoplay=1&cover=1. Если вы хотите вставить этот виджет на вашу страницу, вы можете сделать следующее:  <br/><br/>&lt;script src=&quot;https://unpkg.com/@ungap/custom-elements-builtin&quot;&gt;&lt;/script&gt;<br/>&lt;script type=&quot;module&quot; src=&quot;https://unpkg.com/x-frame-bypass&quot;&gt;&lt;/script&gt;<br/>&lt;iframe is=&quot;x-frame-bypass&quot; src=&quot;https://widgets.kinopoisk.ru/discovery/trailer/167560?onlyPlayer=1&amp;autoplay=1&amp;cover=1&quot; width=&quot;500&quot; height=&quot;500&quot;&gt;&lt;/iframe&gt;</li></ul> */
    get: {
      parameters: {
        path: {
          /** kinopoisk film id */
          id: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            'application/json': components['schemas']['VideoResponse'];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Превышен лимит запросов(или дневной, или общий) */
        402: unknown;
        /** Слишком много запросов. Общий лимит - 20 запросов в секунду */
        429: unknown;
      };
    };
  };
  '/api/v2.2/films/{id}/similars': {
    get: {
      parameters: {
        path: {
          /** kinopoisk film id */
          id: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            'application/json': components['schemas']['RelatedFilmResponse'];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Превышен лимит запросов(или дневной, или общий) */
        402: unknown;
        /** Слишком много запросов. Общий лимит - 20 запросов в секунду */
        429: unknown;
      };
    };
  };
  '/api/v2.2/films/{id}/images': {
    /** Данный эндпоинт возвращает изображения связанные с фильмом с пагинацией. Каждая страница содержит <b>не более чем 20 фильмов</b>.</br> Доступные изображения:</br> <ul> <li>STILL - кадры</li> <li>SHOOTING - изображения со съемок</li> <li>POSTER - постеры</li> <li>FAN_ART - фан-арты</li> <li>PROMO - промо</li> <li>CONCEPT - концепт-арты</li> <li>WALLPAPER - обои</li> <li>COVER - обложки</li> <li>SCREENSHOT - скриншоты</li> </ul> */
    get: {
      parameters: {
        path: {
          /** kinopoisk film id */
          id: number;
        };
        query: {
          /** тип изображения */
          type?:
            | 'STILL'
            | 'SHOOTING'
            | 'POSTER'
            | 'FAN_ART'
            | 'PROMO'
            | 'CONCEPT'
            | 'WALLPAPER'
            | 'COVER'
            | 'SCREENSHOT';
          /** номер страницы */
          page?: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            'application/json': components['schemas']['ImageResponse'];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Превышен лимит запросов(или дневной, или общий) */
        402: unknown;
        /** Слишком много запросов. Общий лимит - 20 запросов в секунду */
        429: unknown;
      };
    };
  };
  '/api/v2.2/films/{id}/reviews': {
    /** Возвращает список рецензии зрителей с пагинацией. Каждая страница содержит не более чем 20 рецензий. */
    get: {
      parameters: {
        path: {
          /** kinopoisk film id */
          id: number;
        };
        query: {
          /** номер страницы */
          page?: number;
          /** тип сортировки */
          order?:
            | 'DATE_ASC'
            | 'DATE_DESC'
            | 'USER_POSITIVE_RATING_ASC'
            | 'USER_POSITIVE_RATING_DESC'
            | 'USER_NEGATIVE_RATING_ASC'
            | 'USER_NEGATIVE_RATING_DESC';
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            'application/json': components['schemas']['ReviewResponse'];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Превышен лимит запросов(или дневной, или общий) */
        402: unknown;
        /** Слишком много запросов. Общий лимит - 20 запросов в секунду */
        429: unknown;
      };
    };
  };
  '/api/v2.2/films/top': {
    /** Возвращает список фильмов с пагинацией. Каждая страница содержит не более чем 20 фильмов. */
    get: {
      parameters: {
        query: {
          /** тип топа или коллекции */
          type?: 'TOP_250_BEST_FILMS' | 'TOP_100_POPULAR_FILMS' | 'TOP_AWAIT_FILMS';
          /** номер страницы */
          page?: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            'application/json': components['schemas']['FilmTopResponse'];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Превышен лимит запросов(или дневной, или общий) */
        402: unknown;
        /** Слишком много запросов. Лимит 5 запроса в секунду */
        429: unknown;
      };
    };
  };
  '/api/v2.2/films/premieres': {
    /** Данный эндпоинт возвращает список кинопремьер. Например https://www.kinopoisk.ru/premiere/ */
    get: {
      parameters: {
        query: {
          /** год релиза */
          year: number;
          /** месяц релиза */
          month:
            | 'JANUARY'
            | 'FEBRUARY'
            | 'MARCH'
            | 'APRIL'
            | 'MAY'
            | 'JUNE'
            | 'JULY'
            | 'AUGUST'
            | 'SEPTEMBER'
            | 'OCTOBER'
            | 'NOVEMBER'
            | 'DECEMBER';
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            'application/json': components['schemas']['PremiereResponse'];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Превышен лимит запросов(или дневной, или общий) */
        402: unknown;
        /** Слишком много запросов. Лимит 5 запросов в секунду */
        429: unknown;
      };
    };
  };
  '/api/v2.2/films/filters': {
    /** Возвращает список id стран и жанров, которые могут быть использованы в /api/v2.2/films */
    get: {
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            'application/json': components['schemas']['FiltersResponse'];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Превышен лимит запросов(или дневной, или общий) */
        402: unknown;
        /** Слишком много запросов. Общий лимит - 20 запросов в секунду */
        429: unknown;
      };
    };
  };
  '/api/v2.2/films': {
    /** Возвращает список фильмов с пагинацией. Каждая страница содержит не более чем 20 фильмов. Данный эндпоинт не возращает более 400 фильмов. <i>Используй /api/v2.2/films/filters чтобы получить id стран и жанров.</i> */
    get: {
      parameters: {
        query: {
          /** список id стран разделенные запятой. Например <i>countries=1,2,3</i>. На данный момент можно указать не более одной страны. */
          countries?: number[];
          /** список id жанров разделенные запятой. Например <i>genres=1,2,3</i>. На данный момент можно указать не более одного жанра. */
          genres?: number[];
          /** сортировка */
          order?: 'RATING' | 'NUM_VOTE' | 'YEAR';
          /** тип фильма */
          type?: 'FILM' | 'TV_SHOW' | 'TV_SERIES' | 'MINI_SERIES' | 'ALL';
          /** минимальный рейтинг */
          ratingFrom?: number;
          /** максимальный рейтинг */
          ratingTo?: number;
          /** минимальный год */
          yearFrom?: number;
          /** максимальный год */
          yearTo?: number;
          /** imdb id */
          imdbId?: string;
          /** ключевое слово, которое встречается в названии фильма */
          keyword?: string;
          /** номер страницы */
          page?: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            'application/json': components['schemas']['FilmSearchByFiltersResponse'];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Превышен лимит запросов(или дневной, или общий) */
        402: unknown;
        /** Слишком много запросов. Лимит 5 запросов в секунду */
        429: unknown;
      };
    };
  };
  '/api/v2.1/films/{id}/sequels_and_prequels': {
    /** tbd */
    get: {
      parameters: {
        path: {
          /** kinopoisk film id */
          id: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            'application/json': components['schemas']['FilmSequelsAndPrequelsResponse'][];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Превышен лимит запросов(или дневной, или общий) */
        402: unknown;
        /** Фильм не найден */
        404: unknown;
        /** Слишком много запросов. Общий лимит - 20 запросов в секунду */
        429: unknown;
      };
    };
  };
  '/api/v2.1/films/search-by-keyword': {
    /** Возвращает список фильмов с пагинацией. Каждая страница содержит не более чем 20 фильмов. */
    get: {
      parameters: {
        query: {
          /** ключивые слова для поиска */
          keyword: string;
          /** номер страницы */
          page?: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            'application/json': components['schemas']['FilmSearchResponse'];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Превышен лимит запросов(или дневной, или общий) */
        402: unknown;
        /** Фильмы не найдены */
        404: unknown;
        /** Слишком много запросов. Лимит 5 запросов в секунду */
        429: unknown;
      };
    };
  };
  '/api/v2.1/films/releases': {
    /** Данный эндпоинт возвращает список цифровых релизов. Например https://www.kinopoisk.ru/comingsoon/digital/ */
    get: {
      parameters: {
        query: {
          /** год релиза */
          year: number;
          /** месяц релиза */
          month:
            | 'JANUARY'
            | 'FEBRUARY'
            | 'MARCH'
            | 'APRIL'
            | 'MAY'
            | 'JUNE'
            | 'JULY'
            | 'AUGUST'
            | 'SEPTEMBER'
            | 'OCTOBER'
            | 'NOVEMBER'
            | 'DECEMBER';
          /** номер страницы */
          page?: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            'application/json': components['schemas']['DigitalReleaseResponse'];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Превышен лимит запросов(или дневной, или общий) */
        402: unknown;
        /** Фильмы не найдены */
        404: unknown;
        /** Слишком много запросов. Лимит 5 запросов в секунду */
        429: unknown;
      };
    };
  };
  '/api/v1/staff': {
    get: {
      parameters: {
        query: {
          /** kinopoisk film id */
          filmId: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            'application/json': components['schemas']['StaffResponse'][];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Превышен лимит запросов(или дневной, или общий) */
        402: unknown;
        /** Данные не найдены */
        404: unknown;
        /** Слишком много запросов. Общий лимит - 20 запросов в секунду */
        429: unknown;
      };
    };
  };
  '/api/v1/staff/{id}': {
    get: {
      parameters: {
        path: {
          /** kinopoisk person id */
          id: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            'application/json': components['schemas']['PersonResponse'];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Превышен лимит запросов(или дневной, или общий) */
        402: unknown;
        /** Данные не найдены */
        404: unknown;
        /** Слишком много запросов. Общий лимит - 20 запросов в секунду */
        429: unknown;
      };
    };
  };
  '/api/v1/persons': {
    /** Одна страница может содержать до 50 элементов в items. */
    get: {
      parameters: {
        query: {
          /** имя человека */
          name: string;
          /** номер страницы */
          page?: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            'application/json': components['schemas']['PersonByNameResponse'];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Превышен лимит запросов(или дневной, или общий) */
        402: unknown;
        /** Слишком много запросов. Общий лимит - 5 запросов в секунду */
        429: unknown;
      };
    };
  };
}

export interface components {
  schemas: {
    Film: {
      /** @example 301 */
      kinopoiskId: number;
      /** @example tt0133093 */
      imdbId: string | null;
      /** @example Матрица */
      nameRu: string | null;
      /** @example The Matrix */
      nameEn: string | null;
      /** @example The Matrix */
      nameOriginal: string | null;
      /** @example https://kinopoiskapiunofficial.tech/images/posters/kp/301.jpg */
      posterUrl: string;
      /** @example https://kinopoiskapiunofficial.tech/images/posters/kp_small/301.jpg */
      posterUrlPreview: string;
      /** @example https://avatars.mds.yandex.net/get-ott/1672343/2a0000016cc7177239d4025185c488b1bf43/orig */
      coverUrl: string | null;
      /** @example https://avatars.mds.yandex.net/get-ott/1648503/2a00000170a5418408119bc802b53a03007b/orig */
      logoUrl: string | null;
      /** @example 293 */
      reviewsCount: number;
      /** @example 88.9 */
      ratingGoodReview: number | null;
      /** @example 257 */
      ratingGoodReviewVoteCount: number | null;
      /** @example 8.5 */
      ratingKinopoisk: number | null;
      /** @example 524108 */
      ratingKinopoiskVoteCount: number | null;
      /** @example 8.7 */
      ratingImdb: number | null;
      /** @example 1729087 */
      ratingImdbVoteCount: number | null;
      /** @example 7.8 */
      ratingFilmCritics: number | null;
      /** @example 155 */
      ratingFilmCriticsVoteCount: number | null;
      /** @example 7.8 */
      ratingAwait: number | null;
      /** @example 2 */
      ratingAwaitCount: number | null;
      /** @example 7.8 */
      ratingRfCritics: number | null;
      /** @example 31 */
      ratingRfCriticsVoteCount: number | null;
      /** @example https://www.kinopoisk.ru/film/301/ */
      webUrl: string;
      /** @example 1999 */
      year: number | null;
      /** @example 136 */
      filmLength: number | null;
      /** @example Добро пожаловать в реальный мир */
      slogan: string | null;
      /** @example Жизнь Томаса Андерсона разделена на две части: */
      description: string | null;
      /** @example Хакер Нео узнает, что его мир — виртуальный. Выдающийся экшен, доказавший, что зрелищное кино может быть умным */
      shortDescription: string | null;
      /** @example Фильм доступен только на языке оригинала с русскими субтитрами */
      editorAnnotation: string | null;
      /** @example false */
      isTicketsAvailable: boolean;
      /**
       * @example POST_PRODUCTION
       * @enum {string|null}
       */
      productionStatus:
        | ('FILMING' | 'PRE_PRODUCTION' | 'COMPLETED' | 'ANNOUNCED' | 'UNKNOWN' | 'POST_PRODUCTION')
        | null;
      /**
       * @example FILM
       * @enum {string}
       */
      type: 'FILM' | 'VIDEO' | 'TV_SERIES' | 'MINI_SERIES' | 'TV_SHOW';
      /** @example r */
      ratingMpaa: string | null;
      /** @example age16 */
      ratingAgeLimits: string | null;
      /** @example false */
      hasImax: boolean | null;
      /** @example false */
      has3D: boolean | null;
      /** @example 2021-07-29T20:07:49.109817 */
      lastSync: string;
      countries: components['schemas']['Country'][];
      genres: components['schemas']['Genre'][];
      /** @example 1996 */
      startYear: number | null;
      /** @example 1996 */
      endYear: number | null;
      /** @example false */
      serial?: boolean | null;
      /** @example false */
      shortFilm?: boolean | null;
      /** @example false */
      completed?: boolean | null;
    } & {
      boxOffice: unknown;
      distributions: unknown;
      facts: unknown;
      seasons: unknown;
    };
    SeasonResponse: {
      /** @example 5 */
      total: number;
      items: components['schemas']['Season'][];
    };
    FactResponse: {
      /** @example 5 */
      total: number;
      items: components['schemas']['Fact'][];
    };
    DistributionResponse: {
      /** @example 5 */
      total: number;
      items: components['schemas']['Distribution'][];
    };
    BoxOfficeResponse: {
      /** @example 5 */
      total: number;
      items: components['schemas']['BoxOffice'][];
    };
    Fact: {
      /** @example В эпизоде, где Тринити и Нео в поисках Морфиуса оказываются на крыше... */
      text: string;
      /**
       * @example BLOOPER
       * @enum {string}
       */
      type: 'FACT' | 'BLOOPER';
      /** @example false */
      spoiler: boolean;
    };
    BoxOffice: {
      /** @example BUDGET */
      type: string;
      /** @example 63000000 */
      amount: number;
      /** @example USD */
      currencyCode: string;
      /** @example US Dollar */
      name: string;
      /** @example $ */
      symbol: string;
    };
    AwardResponse: {
      /** @example 5 */
      total: number;
      items: components['schemas']['Award'][];
    };
    Award: {
      /** @example Оскар */
      name: string;
      /** @example true */
      win: boolean;
      /** @example https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/09035193-2458-4de7-a7df-ad8f85b73798/orig */
      imageUrl: string | null;
      /** @example Лучший звук */
      nominationName: string;
      /** @example 2000 */
      year: number;
      persons?: components['schemas']['AwardPerson'][];
    };
    AwardPerson: {
      /** @example 1937039 */
      kinopoiskId: number;
      /** @example https://www.kinopoisk.ru/name/1937039/ */
      webUrl: string;
      /** @example Джон Т. Рейц */
      nameRu: string | null;
      /** @example John T. Reitz */
      nameEn: string | null;
      /** @example MALE */
      sex: string;
      /** @example https://kinopoiskapiunofficial.tech/images/actor_posters/kp/1937039.jpg */
      posterUrl: string;
      /** @example 178 */
      growth: number | null;
      /** @example 1955-11-02 */
      birthday: string | null;
      /** @example 2019-01-06 */
      death: string | null;
      /** @example 21 */
      age: number | null;
      /** @example Лос-Анджелес, Калифорния, США */
      birthplace: string | null;
      /** @example Лос-Анджелес, Калифорния, США */
      deathplace: string | null;
      /** @example Монтажер, Продюсер */
      profession: string | null;
    };
    Distribution: {
      /**
       * @example PREMIERE
       * @enum {string}
       */
      type: 'LOCAL' | 'COUNTRY_SPECIFIC' | 'PREMIERE' | 'ALL' | 'WORLD_PREMIER';
      /**
       * @example CINEMA
       * @enum {string|null}
       */
      subType: ('CINEMA' | 'DVD' | 'DIGITAL' | 'BLURAY') | null;
      /** @example 1999-05-07 */
      date: string | null;
      /** @example false */
      reRelease: boolean | null;
      country: components['schemas']['Country'] & (unknown | null);
      companies: components['schemas']['Company'][];
    };
    Company: {
      /** @example Каро-Премьер */
      name: string;
    };
    Season: {
      /** @example 1 */
      number: number;
      episodes: components['schemas']['Episode'][];
    };
    Episode: {
      /** @example 1 */
      seasonNumber: number;
      /** @example 1 */
      episodeNumber: number;
      nameRu: string | null;
      /** @example Chapter One: The Vanishing of Will Byers */
      nameEn: string | null;
      /** @example The Vanishing of Will Byers... */
      synopsis: string | null;
      /** @example 2016-07-15 */
      releaseDate: string | null;
    };
    Country: {
      /** @example США */
      country: string;
    };
    Genre: {
      /** @example фантастика */
      genre: string;
    };
    FiltersResponse: {
      genres: components['schemas']['FiltersResponse_genres'][];
      countries: components['schemas']['FiltersResponse_countries'][];
    };
    FilmSearchResponse: {
      /** @example мстители */
      keyword: string;
      /** @example 7 */
      pagesCount: number;
      /** @example 134 */
      searchFilmsCountResult: number;
      films: components['schemas']['FilmSearchResponse_films'][];
    };
    FilmSearchByFiltersResponse: {
      /** @example 7 */
      total: number;
      /** @example 1 */
      totalPages: number;
      items: components['schemas']['FilmSearchByFiltersResponse_items'][];
    };
    FilmSequelsAndPrequelsResponse: {
      /** @example 301 */
      filmId: number;
      /** @example Матрица */
      nameRu: string;
      /** @example The Matrix */
      nameEn: string;
      /** @example The Matrix */
      nameOriginal: string;
      /** @example https://kinopoiskapiunofficial.tech/images/posters/kp/301.jpg */
      posterUrl: string;
      /** @example https://kinopoiskapiunofficial.tech/images/posters/kp_small/301.jpg */
      posterUrlPreview: string;
      /**
       * @example SEQUEL
       * @enum {string}
       */
      relationType: 'SEQUEL' | 'PREQUEL' | 'REMAKE' | 'UNKNOWN';
    };
    RelatedFilmResponse: {
      /** @example 7 */
      total: number;
      items: components['schemas']['RelatedFilmResponse_items'][];
    };
    ReviewResponse: {
      /**
       * @description Суммарное кол-во пользовательских рецензий
       * @example 12
       */
      total: number;
      /** @example 2 */
      totalPages: number;
      /** @example 1 */
      totalPositiveReviews: number;
      /** @example 7 */
      totalNegativeReviews: number;
      /** @example 12 */
      totalNeutralReviews: number;
      items: components['schemas']['ReviewResponse_items'][];
    };
    FilmTopResponse: {
      /** @example 7 */
      pagesCount: number;
      films: components['schemas']['FilmTopResponse_films'][];
    };
    StaffResponse: {
      /** @example 66539 */
      staffId: number;
      /** @example Винс Гиллиган */
      nameRu: string | null;
      /** @example Vince Gilligan */
      nameEn: string | null;
      /** @example Neo */
      description: string | null;
      /** @example https://st.kp.yandex.net/images/actor/66539.jpg */
      posterUrl: string;
      /** @example Режиссеры */
      professionText: string;
      /**
       * @example DIRECTOR
       * @enum {string}
       */
      professionKey:
        | 'WRITER'
        | 'OPERATOR'
        | 'EDITOR'
        | 'COMPOSER'
        | 'PRODUCER_USSR'
        | 'TRANSLATOR'
        | 'DIRECTOR'
        | 'DESIGN'
        | 'PRODUCER'
        | 'ACTOR'
        | 'VOICE_DIRECTOR'
        | 'UNKNOWN';
    };
    PersonResponse: {
      /** @example 66539 */
      personId: number;
      /** @example 10096 */
      webUrl: string | null;
      /** @example Винс Гиллиган */
      nameRu: string | null;
      /** @example Vince Gilligan */
      nameEn: string | null;
      /**
       * @example MALE
       * @enum {string|null}
       */
      sex: ('MALE' | 'FEMALE') | null;
      /** @example https://kinopoiskapiunofficial.tech/images/actor_posters/kp/10096.jpg */
      posterUrl: string;
      /** @example 174 */
      growth: string | null;
      /** @example 1965-04-04 */
      birthday: string | null;
      /** @example 2008-01-22 */
      death: string | null;
      /** @example 55 */
      age: number | null;
      /** @example Манхэттэн, Нью-Йорк, США */
      birthplace: string | null;
      /** @example Манхэттэн, Нью-Йорк, США */
      deathplace: string | null;
      /** @example 1 */
      hasAwards: number | null;
      /** @example Актер, Продюсер, Сценарист */
      profession: string | null;
      facts: string[];
      spouses: components['schemas']['PersonResponse_spouses'][];
      films: components['schemas']['PersonResponse_films'][];
    };
    PersonByNameResponse: {
      /** @example 35 */
      total: number;
      items: components['schemas']['PersonByNameResponse_items'][];
    };
    ImageResponse: {
      /**
       * @description Общее кол-во изображений
       * @example 50
       */
      total: number;
      /**
       * @description Код-во доступных страниц
       * @example 3
       */
      totalPages: number;
      items: components['schemas']['ImageResponse_items'][];
    };
    PremiereResponse: {
      /** @example 34 */
      total: number;
      items: components['schemas']['PremiereResponseItem'][];
    };
    PremiereResponseItem: {
      /** @example 301 */
      kinopoiskId: number;
      /** @example Дитя погоды */
      nameRu: string | null;
      /** @example Tenki no ko */
      nameEn: string | null;
      /** @example 2019 */
      year: number;
      /** @example http://kinopoiskapiunofficial.tech/images/posters/kp/1219417.jpg */
      posterUrl: string;
      /** @example https://kinopoiskapiunofficial.tech/images/posters/kp_small/301.jpg */
      posterUrlPreview: string;
      countries: components['schemas']['Country'][];
      genres: components['schemas']['Genre'][];
      /** @example 112 */
      duration: number | null;
      /** @example 2020-06-01 */
      premiereRu: string;
    };
    DigitalReleaseResponse: {
      /** @example 1 */
      page: number;
      /** @example 34 */
      total: number;
      releases: components['schemas']['DigitalReleaseItem'][];
    };
    DigitalReleaseItem: {
      /** @example 301 */
      filmId: number;
      /** @example Дитя погоды */
      nameRu: string;
      /** @example Tenki no ko */
      nameEn: string;
      /** @example 2019 */
      year: number;
      /** @example http://kinopoiskapiunofficial.tech/images/posters/kp/1219417.jpg */
      posterUrl: string;
      /** @example https://kinopoiskapiunofficial.tech/images/posters/kp_small/301.jpg */
      posterUrlPreview: string;
      countries: components['schemas']['Country'][];
      genres: components['schemas']['Genre'][];
      /** @example 7.962 */
      rating: number;
      /** @example 14502 */
      ratingVoteCount: number;
      /** @example 99.13 */
      expectationsRating: number;
      /** @example 1123 */
      expectationsRatingVoteCount: number;
      /** @example 112 */
      duration: number;
      /** @example 2020-06-01 */
      releaseDate: string;
    };
    VideoResponse: {
      /** @example 50 */
      total: number;
      items: components['schemas']['VideoResponse_items'][];
    };
    ApiError: {
      /** @example User test@test.ru is inactive or deleted. */
      message: string;
    };
    /** @example null */
    FiltersResponse_genres: {
      /** @example 1 */
      id?: number;
      /** @example боевик */
      genre?: string;
    };
    /** @example null */
    FiltersResponse_countries: {
      /** @example 1 */
      id?: number;
      /** @example США */
      country?: string;
    };
    /** @example null */
    FilmSearchResponse_films: {
      /** @example 263531 */
      filmId?: number;
      /** @example Мстители */
      nameRu?: string;
      /** @example The Avengers */
      nameEn?: string;
      /**
       * @example FILM
       * @enum {string}
       */
      type?: 'FILM' | 'TV_SHOW' | 'UNKNOWN';
      /** @example 2012 */
      year?: string;
      /** @example США, Джосс Уидон(фантастика) */
      description?: string;
      /** @example 2:17 */
      filmLength?: string;
      countries?: components['schemas']['Country'][];
      genres?: components['schemas']['Genre'][];
      /** @example NOTE!!! 7.9 for released film or 99% if film have not released yet */
      rating?: string;
      /** @example 284245 */
      ratingVoteCount?: number;
      /** @example http://kinopoiskapiunofficial.tech/images/posters/kp/263531.jpg */
      posterUrl?: string;
      /** @example https://kinopoiskapiunofficial.tech/images/posters/kp_small/301.jpg */
      posterUrlPreview?: string;
    };
    /** @example null */
    FilmSearchByFiltersResponse_items: {
      /** @example 263531 */
      kinopoiskId?: number;
      /** @example tt0050561 */
      imdbId?: string | null;
      /** @example Мстители */
      nameRu?: string | null;
      /** @example The Avengers */
      nameEn?: string | null;
      /** @example The Avengers */
      nameOriginal?: string | null;
      countries?: components['schemas']['Country'][];
      genres?: components['schemas']['Genre'][];
      /** @example 7.9 */
      ratingKinopoisk?: number | null;
      /** @example 7.9 */
      ratingImdb?: number | null;
      /** @example 2012 */
      year?: number | null;
      /**
       * @example FILM
       * @enum {string}
       */
      type?: 'FILM' | 'TV_SHOW' | 'VIDEO' | 'MINI_SERIES' | 'TV_SERIES' | 'UNKNOWN';
      /** @example http://kinopoiskapiunofficial.tech/images/posters/kp/263531.jpg */
      posterUrl?: string;
      /** @example https://kinopoiskapiunofficial.tech/images/posters/kp_small/301.jpg */
      posterUrlPreview?: string;
    };
    /** @example null */
    RelatedFilmResponse_items: {
      /** @example 301 */
      filmId?: number;
      /** @example Матрица */
      nameRu?: string | null;
      /** @example The Matrix */
      nameEn?: string | null;
      /** @example The Matrix */
      nameOriginal?: string | null;
      /** @example https://kinopoiskapiunofficial.tech/images/posters/kp/301.jpg */
      posterUrl?: string;
      /** @example https://kinopoiskapiunofficial.tech/images/posters/kp_small/301.jpg */
      posterUrlPreview?: string;
      /**
       * @example SIMILAR
       * @enum {string}
       */
      relationType?: 'SIMILAR';
    };
    /** @example null */
    ReviewResponse_items: {
      /** @example 2 */
      kinopoiskId?: number;
      /** @enum {string} */
      type?: 'POSITIVE' | 'NEGATIVE' | 'NEUTRAL' | 'UNKNOWN';
      /** @example 2010-09-05T20:37:00 */
      date?: string;
      /** @example 122 */
      positiveRating?: number;
      /** @example 12 */
      negativeRating?: number;
      /** @example Username */
      author?: string;
      /** @example Title */
      title?: string | null;
      /** @example text */
      description?: string;
    };
    /** @example null */
    FilmTopResponse_films: {
      /** @example 263531 */
      filmId?: number;
      /** @example Мстители */
      nameRu?: string | null;
      /** @example The Avengers */
      nameEn?: string | null;
      /** @example 2012 */
      year?: string | null;
      /** @example 137 */
      filmLength?: string | null;
      countries?: components['schemas']['Country'][];
      genres?: components['schemas']['Genre'][];
      /** @example 7.9 */
      rating?: number | null;
      /** @example 284245 */
      ratingVoteCount?: number | null;
      /** @example http://kinopoiskapiunofficial.tech/images/posters/kp/263531.jpg */
      posterUrl?: string;
      /** @example https://kinopoiskapiunofficial.tech/images/posters/kp_small/301.jpg */
      posterUrlPreview?: string;
    };
    /** @example null */
    PersonResponse_spouses: {
      /** @example 32169 */
      personId?: number;
      /** @example Сьюзан Дауни */
      name?: string | null;
      /** @example false */
      divorced?: boolean;
      /** @example */
      divorcedReason?: string | null;
      /**
       * @example MALE
       * @enum {string}
       */
      sex?: 'MALE' | 'FEMALE';
      /** @example 2 */
      children?: number;
      /** @example https://www.kinopoisk.ru/name/32169/ */
      webUrl?: string;
      /** @example супруга */
      relation?: string;
    };
    /** @example null */
    PersonResponse_films: {
      /** @example 32169 */
      filmId?: number;
      /** @example Солист */
      nameRu?: string | null;
      /** @example The Soloist */
      nameEn?: string | null;
      /** @example 7.2 or 76% if film has not released yet */
      rating?: string | null;
      /** @example false */
      general?: boolean;
      /** @example Steve Lopez */
      description?: string | null;
      /**
       * @example ACTOR
       * @enum {string}
       */
      professionKey?:
        | 'WRITER'
        | 'OPERATOR'
        | 'EDITOR'
        | 'COMPOSER'
        | 'PRODUCER_USSR'
        | 'HIMSELF'
        | 'HERSELF'
        | 'HRONO_TITR_MALE'
        | 'HRONO_TITR_FEMALE'
        | 'TRANSLATOR'
        | 'DIRECTOR'
        | 'DESIGN'
        | 'PRODUCER'
        | 'ACTOR'
        | 'VOICE_DIRECTOR'
        | 'UNKNOWN';
    };
    /** @example null */
    PersonByNameResponse_items: {
      /** @example 66539 */
      kinopoiskId?: number;
      /** @example 10096 */
      webUrl?: string;
      /** @example Винс Гиллиган */
      nameRu?: string | null;
      /** @example Vince Gilligan */
      nameEn?: string | null;
      /**
       * @example MALE
       * @enum {string|null}
       */
      sex?: ('MALE' | 'FEMALE' | 'UNKNOWN') | null;
      /** @example https://kinopoiskapiunofficial.tech/images/actor_posters/kp/10096.jpg */
      posterUrl?: string;
    };
    /** @example null */
    ImageResponse_items: {
      /** @example https://avatars.mds.yandex.net/get-kinopoisk-image/4303601/2924f6c4-4ea0-4a1d-9a48-f29577172b27/orig */
      imageUrl?: string;
      /** @example https://avatars.mds.yandex.net/get-kinopoisk-image/4303601/2924f6c4-4ea0-4a1d-9a48-f29577172b27/300x */
      previewUrl?: string;
    };
    /** @example null */
    VideoResponse_items: {
      /** @example https://www.youtube.com/watch?v=gbcVZgO4n4E */
      url?: string;
      /** @example Мстители: Финал – официальный трейлер (16+) */
      name?: string;
      /**
       * @example YOUTUBE
       * @enum {string}
       */
      site?: 'YOUTUBE' | 'KINOPOISK_WIDGET' | 'UNKNOWN';
    };
  };
}

export interface operations {}

export interface external {}
